"""Emit C99: message ids, structs, and bit-exact pack/unpack functions.

Struct fields hold the raw (pre-scale) integer a signal carries on the wire,
not the physical value - firmware on a CAN transceiver doesn't get to assume
an FPU, and the conversion is one multiply-add away for whoever needs it.
Scale, offset and unit go in a comment beside the field instead.

`pack()`/`unpack()` are generated straight off `CanSignal.bit_mapping()` -
the same mapping `spec.py` uses to validate overlaps - one bit per emitted
line. That is more verbose than a hand-rolled shift-and-mask, but every line
is independently checkable against the DBC bit position it came from, which
matters more here since this file is not compiled in CI to catch a mistake.
"""

from __future__ import annotations

from xforge.comms.spec import CanBus, CanMessage, CanSignal, valid_identifier

_WIDTHS = (8, 16, 32, 64)


def _c_width(length: int) -> int:
    for w in _WIDTHS:
        if length <= w:
            return w
    raise ValueError(f"signal length {length} exceeds the 64-bit width a CAN frame allows")


def _c_type(sig: CanSignal) -> str:
    return f"{'int' if sig.is_signed else 'uint'}{_c_width(sig.length)}_t"


def _u_type(sig: CanSignal) -> str:
    return f"uint{_c_width(sig.length)}_t"


def _suffix(width: int) -> str:
    return "ULL" if width == 64 else "u"


def _enum_member(msg: CanMessage, sig: CanSignal, label: str) -> str:
    safe = "".join(c if c.isalnum() else "_" for c in label).upper()
    if safe and safe[0].isdigit():
        safe = "_" + safe
    return f"{msg.name.upper()}_{sig.name.upper()}_{safe}"


def _struct_name(msg: CanMessage) -> str:
    return f"{valid_identifier(msg.name)}_t"


def _fn_prefix(msg: CanMessage) -> str:
    """Function names are lower_snake regardless of the message's own
    casing - struct/enum names keep the spec's casing, C function names
    don't, and readers expect that split."""
    return valid_identifier(msg.name).lower()


def _guard(bus: CanBus) -> str:
    return f"XFORGE_COMMS_{bus.name.upper()}_H"


def generate_header(bus: CanBus, source_name: str = "the comms spec") -> str:
    """The `.h`: ids, DLCs, structs, value-table defines, function decls."""
    lines: list[str] = [
        f"/* Generated by xforge comms from {source_name}.",
        " * Do not hand-edit - the YAML spec is the source of truth. */",
        f"#ifndef {_guard(bus)}",
        f"#define {_guard(bus)}",
        "",
        "#include <stdint.h>",
        "",
        f"/* Bus: {bus.name}, {bus.bitrate} bit/s, "
        f"{bus.addressing}{' FD' if bus.fd else ''} */",
        "",
    ]

    for msg in bus.messages:
        name = valid_identifier(msg.name)
        lines.append(f"#define {name.upper()}_ID {hex(msg.id)}u")
        lines.append(f"#define {name.upper()}_DLC {msg.dlc}u")
        if msg.cycle_time_ms is not None:
            lines.append(f"#define {name.upper()}_CYCLE_TIME_MS {msg.cycle_time_ms}u")
        lines.append("")

        for sig in msg.signals:
            if not sig.values:
                continue
            for raw, label in sorted(sig.values.items()):
                lines.append(f"#define {_enum_member(msg, sig, label)} {raw}")
            lines.append("")

        lines.append(f"typedef struct {{")
        for sig in msg.signals:
            end_bit = sig.start_bit + (sig.length - 1 if sig.byte_order == "little" else 0)
            comment = (
                f"bits {sig.start_bit}..{end_bit} ({sig.byte_order}-endian); "
                f"physical = raw * {sig.scale} + {sig.offset}"
                + (f" {sig.unit}" if sig.unit else "")
            )
            lines.append(f"    {_c_type(sig)} {valid_identifier(sig.name)};  /* {comment} */")
        lines.append(f"}} {_struct_name(msg)};")
        lines.append("")

        fn = _fn_prefix(msg)
        lines.append(f"void {fn}_pack(uint8_t data[{msg.dlc}], const {_struct_name(msg)} *msg);")
        lines.append(f"void {fn}_unpack({_struct_name(msg)} *msg, const uint8_t data[{msg.dlc}]);")
        lines.append("")

    lines.append(f"#endif /* {_guard(bus)} */")
    return "\n".join(lines).rstrip() + "\n"


def _pack_block(sig: CanSignal) -> list[str]:
    utype = _u_type(sig)
    name = valid_identifier(sig.name)
    out = [f"    {{", f"        {utype} raw = ({utype})msg->{name};"]
    for i, p in sig.bit_mapping():
        out.append(
            f"        if ((raw >> {i}) & 1u) data[{p // 8}] |= (uint8_t)(1u << {p % 8});"
        )
    out.append("    }")
    return out


def _unpack_block(sig: CanSignal) -> list[str]:
    utype = _u_type(sig)
    width = _c_width(sig.length)
    ctype = _c_type(sig)
    name = valid_identifier(sig.name)
    one = f"1{_suffix(width)}"
    out = [f"    {{", f"        {utype} raw = 0;"]
    for i, p in sig.bit_mapping():
        out.append(
            f"        if (data[{p // 8}] & (uint8_t)(1u << {p % 8})) raw |= ({utype})({one} << {i});"
        )
    if sig.is_signed and sig.length < width:
        # Sign-extend: both masks are computed here, at generation time, as
        # plain literals - shifting by a *value* known only at generation
        # time (not by a variable at runtime) is what keeps this free of the
        # undefined behaviour a "shift by (width - length)" trick risks for
        # 8/16-bit types, where '~0' promotes to a signed int first.
        sign_bit = (1 << (sig.length - 1))
        high_mask = ((1 << width) - 1) & ~((1 << sig.length) - 1)
        suf = _suffix(width)
        out.append(f"        if (raw & {hex(sign_bit)}{suf}) {{")
        out.append(f"            raw |= {hex(high_mask)}{suf};")
        out.append("        }")
    out.append(f"        msg->{name} = ({ctype})raw;")
    out.append("    }")
    return out


def generate_source(bus: CanBus, header_name: str) -> str:
    """The `.c`: `memset`-and-OR pack, and read-and-assemble unpack."""
    lines: list[str] = [
        f'#include "{header_name}"',
        "#include <string.h>",
        "",
    ]
    for msg in bus.messages:
        fn = _fn_prefix(msg)
        struct = _struct_name(msg)

        lines.append(f"void {fn}_pack(uint8_t data[{msg.dlc}], const {struct} *msg)")
        lines.append("{")
        lines.append(f"    memset(data, 0, {msg.dlc});")
        for sig in msg.signals:
            lines.extend(_pack_block(sig))
        lines.append("}")
        lines.append("")

        lines.append(f"void {fn}_unpack({struct} *msg, const uint8_t data[{msg.dlc}])")
        lines.append("{")
        for sig in msg.signals:
            lines.extend(_unpack_block(sig))
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
